// <auto-generated />
namespace FlightSchedule.Persistence.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialFlightAndRoute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialFlightAndRoute));
        
        string IMigrationMetadata.Id
        {
            get { return "201807061030333_InitialFlightAndRoute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
